### ISSUE TITLE
1.20.1 FORGE 47.1.0 - 1.43 Crashes with Valkyrien Skies 1.20.1 MOD loaded

### ISSUE THREAD

**Issue by Bannta** [Matyrobbrt/GroovyModLoader#23]
GroovyModLoader appears to conflict with Valkyrien Skies mod causing a hard Game Crashed Error in the client with an Exit Code 1. 

During Forge compiling function  "Scanning Mod Candidates"
Everything appears to map properly then it goes into the scanning mod candidates and immediately crashes the client. 
[22:31:00] [main/INFO]: Starting runtime mappings setup...
[22:31:00] [main/INFO]: Injecting ScriptModLocator candidates...
[22:31:00] [main/INFO]: Injected Jimfs file system
[22:31:00] [main/INFO]: Injected ScriptModLocator mod candidates. Found 0 valid mod candidates and 0 broken mod files.
[22:31:01] [GML Mappings Thread/INFO]: Loaded runtime mappings in 1139ms
[22:31:01] [GML Mappings Thread/INFO]: Finished runtime mappings setup.
<then nothing follows, crash>
[latest.log](https://github.com/GroovyMC/GroovyModLoader/files/12354426/latest.log)

No crash reports logged

Modpack: https://legacy.curseforge.com/minecraft/modpacks/hopcraft-1-20-1 

Testing run on 1-20-1-3.0, however, I narrow it down recently to the GML mod I believe on version 2.2
[HopCraft-1.20.1-3.0 [FORGE]](https://legacy.curseforge.com/minecraft/modpacks/hopcraft-1-20-1/files/4705528)
You can use this, just add GML to it. 

I hope this helps, I really like the Eating Animation mod. Unfortunately playing my modpack as a vampire so I'm not currently eating much food at the moment. 
Regards,

**Comment by HereToSaySomething** [comment]
I also am having this same issue.

**Comment by lukebemish** [comment]
Can you confirm whether the issue persists with the new GML version, 4.0.9? I'll try to look into it

**Comment by lukebemish** [comment]
Closing this issue due to inactivity; given that quite a lot of issues regarding mappings were fixed with 4.0.9 (and 4.0.10), I'll assume this was too. Feel free to re-open it with more information, and a log with one of those versions.

**Comment by oOBoomberOo** [comment]
I can confirm having the same issue when using both Valkyrien Skies and GML in **4.0.9**.

Strangely, the actual error message did not get logged into the log or crash report file, but it does appear in Launcher's output, which is related to a missing Jackson module.

```
main | Successfully made module authlib transformable
GML Mappings Thread | Loaded runtime mappings in 1404ms
GML Mappings Thread | Finished runtime mappings setup.
--- message after this line do not appear in latest.log
main | Exception in thread "main" java.lang.module.FindException: Module com.fasterxml.jackson.core not found, required by com.fasterxml.jackson.module.paramnames
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

![image](https://github.com/GroovyMC/GroovyModLoader/assets/26600816/bf33a3b6-bf42-4d3b-8100-a266b9305fa2)

## Mod Used
- gml-4.0.9-all.jar
- create-1.20.1-0.5.1.f.jar
- valkyrienskies-120-2.1.3-beta.1.jar
- create_interactive-1201-forge-1.0.2-beta.1.jar

**Comment by lukebemish** [comment]
This appears to be due to us moving Jackson to a LIBRARY while the one Valkyrien Skies includes gets it's stuff shoved on GAMELIBRARY. We're looking into solutions, though this is not an easy one to solve

**Comment by lukebemish** [comment]
This should be fixed on neoforge 1.20.5 once we get this released for that version; I will be looking into fixes for older versions, but unfortunately there's not much we can do there in a clean way.

**Comment by snowleopardd** [comment]
getting the same crash

**Comment by lukebemish** [comment]
This should not be an issue on the neoforge 1.21 release of GML; there is nothing that we can do to fix this on mcforge 1.20.1 unless mcforge themselves fix it. They've recently made a change to the jarJar system on a newer version -- which it appears they're backporting? -- that will load jarJar-ed libraries on the layer of their parent (that is, the ones we bundle would be loaded as LIBRARY not GAMELIBRARY). However, this does not actually fix the issue -- we need the ones Valkyrien Skies bundles to be loaded as LIBRARY even if Valkyrien Skies is itself a mod that loads on the game layer, and bundles a newer version. Having watched attempts to change the behavior necessary to fix this with the mcforge folks fall through, and having inspected how everything gets loaded, there does not appear to be any solution to this in 1.20.1, even a fairly hacky one. We could probably do some `Unsafe` schenanigans to move around modues after the fact, but, frankly, that sounds like a Bad Idea on so many levels. Valkyrien Skies could fix this on their end by manually marking the relevant libraries, and anything that provides services they load, as `FMLModType: LIBRARY`, though really the system ought to be designed to not require that level of work from an unrelated mod. I will leave this issue open, but at present I do not forsee this being fixed on our end in 1.20.1.

**Comment by TimberTheSilly** [comment]
I tried to load my modpack, and it gave error code 1, and I had the create mod downloaded. So, if its error code 1 it could also be the create mod? I don't really know what I am doing as I am a new person but I'm trying to help as much as I can!

**Comment by lukebemish** [comment]
I am not at all sure what that would have to do with this issue at all. If you have a similar issue, please open a _new_ issue _with logs_ so that we can see what the issue is.

**Comment by RHINE-LAB-Muelsyse** [comment]
> 我完全不确定这与这个问题有什么关系。如果您有类似的问题，请打开_一个新的 Issue（包含日志_），以便我们查看问题所在。

I might have misunderstood some parts: Does the discussion result of this issue indicate that Forge needs to resolve this compatibility problem? Should I submit a new issue to Forge, including a link to this one?

**Comment by lukebemish** [comment]
Forge would need to resolve this and they have actively stated that they do not intend to resolve it in a working fashion. So, this cannot be fixed -- the only people who can are mcforge, and they have said that they do not want to, and implemented a non-functional "fix" for a different edge case instead. NeoForge, on newer versions, has already fixed this.

**Comment by lukebemish** [comment]
Just making this clear as I've seen a bit of misinformation being spread some places: this isn't a "we won't fix this" case, this is a "we literally _cannot_ fix this" case. The only two solutions are for (a) everyone who bundles jackson to transform those jars to be LIBRARY, or (b) a breaking change on mcforge's end to make LIBRARY the default place for JiJed stuff. Neither of those are great, TBH; a breaking change in mcforge is not going to happen within an existing MC version, and the former fix is something that would have to be implemented by anyone else consuming jackson which... generally sucks. If the Valkyrien Skies folks have any interest in implementing the former of those fixes on their end, which _would_ fix the issue (not that they should _need_ to do that, but, well, there's limitations with mcforge in that regard), I am more than willing to help figure out how -- otherwise, that's about all that can be done as far as I am aware, so I am going to close this as won't-fix -- not because we don't want to but because in the versions this effects, it is literally impossible to fix from our end.

**Comment by Rubydesic** [comment]
@lukebemish If you are offering to fix it, we (Valkyrien Skies) would absolutely accept a PR.

**Comment by lukebemish** [comment]
I mostly consider these old versions to be dead and on life support so that is pretty low on my priority list, though I can certainly poke it if I have time; that said, the details for anyone else this may interest: fixing this "properly" on that end requires transforming the jarJar-ed jars in Vallyrien Skies for the specific conflicting dependencies here (and anything coupled to them by service implementation) to add `FMLModType: LIBRARY` to their manifests. This should be safe generally speaking; however, note that it would theoretically open you up to other incompatibilities if someone else jarJars a library you don't that implements a service from one of those libraries.

**Comment by Tim-Conner** [comment]
I've run into the exact same issue too – Valkyrien Skies throws an error when used alongside GroovyModLoader, but surprisingly, everything works perfectly fine when Neruina is added into the mix with these two mods.

**Comment by Xplodin** [comment]
heads up Neruina no longer fixes the issue with versions ABOVE 2.1.2 for 1.20.1. itll go back to crashing
